apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-questoes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-questoes
  template:
    metadata:
      labels:
        app: frontend-questoes
    spec:
      containers:
        - name: frontend
          image: phenriquernagel/frontend-questoes:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: API_URL
              value: "http://api-questoes.api-questoes.svc.cluster.local/docs"
