apiVersion: v1
kind: Service
metadata:
  name: frontend-questoes
spec:
  type: {{ .Values.service.type }}
  selector:
    app: frontend-questoes
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
