apiVersion: v2
name: api-questions
description: Helm chart para a API de Questões - Uma plataforma para gerenciamento de perguntas e respostas
version: 1.0.0
appVersion: 1.0.0
maintainers:
  - name: Pedro Henrique Rangel
    email: exemplo@email.com

dependencies:
  - name: postgresql
    version: 12.1.1
    repository: https://charts.bitnami.com/bitnami
