api:
  replicaCount: 2
  image:
    repository: yourdockerhub/api-questions
    tag: latest
  service:
    type: ClusterIP
    port: 80

postgresql:
  enabled: true
  postgresqlUsername: postgres
  postgresqlPassword: password
  postgresqlDatabase: questions
  persistence:
    enabled: true
    size: 1Gi

externalDatabase:
  enabled: false
  host: external-db-host
  port: 5432
  user: external-user
  password: external-password
  database: external-db