apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-questoes
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: api-questoes
  template:
    metadata:
      labels:
        app: api-questoes
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: api-questoes
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: database_url
