{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-questoes
spec:
  rules:
    - host: api.seudominio.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-questoes
                port:
                  number: 8000
{{- end }}
