apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-pdf-pvc
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
