apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-questoes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-questoes
  template:
    metadata:
      labels:
        app: api-questoes
    spec:
      containers:
        - name: api
          image: phenriquernagel/api-questoes:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "postgresql://appuser:pedro@123@postgres:5432/questoes"
          volumeMounts:
            - name: pdfs
              mountPath: /pdfs
      volumes:
        - name: pdfs
          persistentVolumeClaim:
            claimName: shared-pdf-pvc
