replicaCount: 1
image:
  repository: phenriquernagel/questoes-backend
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8000
env:
  POSTGRES_HOST: "postgres.backend.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "questoes"
  POSTGRES_USER: "questuser"
  POSTGRES_PASSWORD: "questpass"