replicaCount: 1

image:
  repository: phenriquernagel/api-questoes
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  port: 80

postgres:
  user: appuser
  password: pedro123
  db: questoes

rbac:
  create: true

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
