apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  labels:
    app: api-questions
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
data:
  # Nome do banco de dados
  db_name: {{ if .Values.postgresql.enabled }}{{ .Values.postgresql.auth.database }}{{ else }}{{ .Values.externalDatabase.database }}{{ end }}
  # Configurações adicionais da aplicação
  app_environment: {{ .Values.api.environment | default "production" }}
  log_level: {{ .Values.api.logLevel | default "info" }}
