apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
data:
  db_user: {{ .Values.postgresql.postgresqlUsername | b64enc }}
  db_password: {{ .Values.postgresql.postgresqlPassword | b64enc }}