apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  labels:
    app: api-questions
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
type: Opaque
# Nota: Em um ambiente real, estes valores devem ser gerados externamente
# e não armazenados no repositório. Aqui estão apenas como exemplo.
data:
  username: {{ "app_user" | b64enc }}
  postgres-password: {{ randAlphaNum 16 | b64enc }}
  user-password: {{ randAlphaNum 16 | b64enc }}
