apiVersion: v1
kind: Service
metadata:
  name: api-questions-service
  labels:
    app: api-questions
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: api-questions
    release: "{{ .Release.Name }}"
